# Generated by Django 3.2.4 on 2021-06-03 14:27

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=django_cryptography.fields.encrypt(models.FileField(upload_to='static/documents/')),
        ),
    ]
