# Generated by Django 3.2.4 on 2021-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
